jobs:
  do-the-twist:
    name: Do the Twist
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        architecture: ${{ matrix.python-architecture }}
        python-version: ${{ matrix.python-version }}
    - run: python testme.py
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: macos-11
          python-architecture: x64
          python-version: 3.11.0-alpha.2
        - os: macos-10.15
          python-architecture: x64
          python-version: 3.11.0-alpha.2
        - os: ubuntu-20.04
          python-architecture: x64
          python-version: 3.11.0-alpha.2
        - os: ubuntu-18.04
          python-architecture: x64
          python-version: 3.11.0-alpha.2
        - os: ubuntu-20.04
          python-architecture: x64
          python-version: 3.11.0-alpha.2
        - os: ubuntu-18.04
          python-architecture: x64
          python-version: 3.11.0-alpha.2
        - os: windows-2022
          python-architecture: x64
          python-version: 3.11.0-alpha.2
        - os: windows-2019
          python-architecture: x64
          python-version: 3.11.0-alpha.2
        - os: windows-2016
          python-architecture: x64
          python-version: 3.11.0-alpha.2
        - os: windows-2022
          python-architecture: x86
          python-version: 3.11.0-alpha.2
        - os: windows-2019
          python-architecture: x86
          python-version: 3.11.0-alpha.2
        - os: windows-2016
          python-architecture: x86
          python-version: 3.11.0-alpha.2
        - os: macos-11
          python-architecture: x64
          python-version: 3.10.0
        - os: macos-10.15
          python-architecture: x64
          python-version: 3.10.0
        - os: ubuntu-20.04
          python-architecture: x64
          python-version: 3.10.0
        - os: ubuntu-18.04
          python-architecture: x64
          python-version: 3.10.0
        - os: ubuntu-20.04
          python-architecture: x64
          python-version: 3.10.0
        - os: ubuntu-18.04
          python-architecture: x64
          python-version: 3.10.0
        - os: windows-2022
          python-architecture: x64
          python-version: 3.10.0
        - os: windows-2019
          python-architecture: x64
          python-version: 3.10.0
        - os: windows-2016
          python-architecture: x64
          python-version: 3.10.0
        - os: windows-2022
          python-architecture: x86
          python-version: 3.10.0
        - os: windows-2019
          python-architecture: x86
          python-version: 3.10.0
        - os: windows-2016
          python-architecture: x86
          python-version: 3.10.0
        - os: macos-11
          python-architecture: x64
          python-version: 3.9.9
        - os: macos-10.15
          python-architecture: x64
          python-version: 3.9.9
        - os: ubuntu-20.04
          python-architecture: x64
          python-version: 3.9.9
        - os: ubuntu-18.04
          python-architecture: x64
          python-version: 3.9.9
        - os: ubuntu-20.04
          python-architecture: x64
          python-version: 3.9.9
        - os: ubuntu-18.04
          python-architecture: x64
          python-version: 3.9.9
        - os: windows-2022
          python-architecture: x64
          python-version: 3.9.9
        - os: windows-2019
          python-architecture: x64
          python-version: 3.9.9
        - os: windows-2016
          python-architecture: x64
          python-version: 3.9.9
        - os: windows-2022
          python-architecture: x86
          python-version: 3.9.9
        - os: windows-2019
          python-architecture: x86
          python-version: 3.9.9
        - os: windows-2016
          python-architecture: x86
          python-version: 3.9.9
        - os: macos-11
          python-architecture: x64
          python-version: 3.8.12
        - os: macos-10.15
          python-architecture: x64
          python-version: 3.8.12
        - os: ubuntu-20.04
          python-architecture: x64
          python-version: 3.8.12
        - os: ubuntu-18.04
          python-architecture: x64
          python-version: 3.8.12
        - os: ubuntu-20.04
          python-architecture: x64
          python-version: 3.8.12
        - os: ubuntu-18.04
          python-architecture: x64
          python-version: 3.8.12
        - os: macos-11
          python-architecture: x64
          python-version: 3.7.12
        - os: macos-10.15
          python-architecture: x64
          python-version: 3.7.12
        - os: ubuntu-20.04
          python-architecture: x64
          python-version: 3.7.12
        - os: ubuntu-18.04
          python-architecture: x64
          python-version: 3.7.12
        - os: ubuntu-20.04
          python-architecture: x64
          python-version: 3.7.12
        - os: ubuntu-18.04
          python-architecture: x64
          python-version: 3.7.12
        - os: macos-11
          python-architecture: x64
          python-version: 3.6.15
        - os: macos-10.15
          python-architecture: x64
          python-version: 3.6.15
        - os: ubuntu-20.04
          python-architecture: x64
          python-version: 3.6.15
        - os: ubuntu-18.04
          python-architecture: x64
          python-version: 3.6.15
        - os: ubuntu-20.04
          python-architecture: x64
          python-version: 3.6.15
        - os: ubuntu-18.04
          python-architecture: x64
          python-version: 3.6.15
        - os: macos-11
          python-architecture: x64
          python-version: 3.5.10
        - os: macos-10.15
          python-architecture: x64
          python-version: 3.5.10
        - os: ubuntu-20.04
          python-architecture: x64
          python-version: 3.5.10
        - os: ubuntu-18.04
          python-architecture: x64
          python-version: 3.5.10
        - os: ubuntu-20.04
          python-architecture: x64
          python-version: 3.5.10
        - os: ubuntu-18.04
          python-architecture: x64
          python-version: 3.5.10
        - os: ubuntu-20.04
          python-architecture: x64
          python-version: 3.5.10
        - os: ubuntu-18.04
          python-architecture: x64
          python-version: 3.5.10
        - os: ubuntu-20.04
          python-architecture: x64
          python-version: 3.4.10
        - os: ubuntu-18.04
          python-architecture: x64
          python-version: 3.4.10
        - os: ubuntu-20.04
          python-architecture: x64
          python-version: 3.3.7
        - os: ubuntu-18.04
          python-architecture: x64
          python-version: 3.3.7
        - os: windows-2022
          python-architecture: x64
          python-version: 3.2.5
        - os: windows-2019
          python-architecture: x64
          python-version: 3.2.5
        - os: windows-2016
          python-architecture: x64
          python-version: 3.2.5
        - os: windows-2022
          python-architecture: x86
          python-version: 3.2.5
        - os: windows-2019
          python-architecture: x86
          python-version: 3.2.5
        - os: windows-2016
          python-architecture: x86
          python-version: 3.2.5
        - os: windows-2022
          python-architecture: x64
          python-version: 3.1.4
        - os: windows-2019
          python-architecture: x64
          python-version: 3.1.4
        - os: windows-2016
          python-architecture: x64
          python-version: 3.1.4
        - os: windows-2022
          python-architecture: x86
          python-version: 3.1.4
        - os: windows-2019
          python-architecture: x86
          python-version: 3.1.4
        - os: windows-2016
          python-architecture: x86
          python-version: 3.1.4
        - os: windows-2022
          python-architecture: x64
          python-version: 3.0.1
        - os: windows-2019
          python-architecture: x64
          python-version: 3.0.1
        - os: windows-2016
          python-architecture: x64
          python-version: 3.0.1
        - os: windows-2022
          python-architecture: x86
          python-version: 3.0.1
        - os: windows-2019
          python-architecture: x86
          python-version: 3.0.1
        - os: windows-2016
          python-architecture: x86
          python-version: 3.0.1
        - os: macos-11
          python-architecture: x64
          python-version: 2.7.18
        - os: macos-10.15
          python-architecture: x64
          python-version: 2.7.18
        - os: ubuntu-20.04
          python-architecture: x64
          python-version: 2.7.18
        - os: ubuntu-18.04
          python-architecture: x64
          python-version: 2.7.18
        - os: ubuntu-20.04
          python-architecture: x64
          python-version: 2.7.18
        - os: ubuntu-18.04
          python-architecture: x64
          python-version: 2.7.18
        - os: ubuntu-20.04
          python-architecture: x64
          python-version: 2.7.18
        - os: ubuntu-18.04
          python-architecture: x64
          python-version: 2.7.18
        - os: windows-2022
          python-architecture: x64
          python-version: 2.7.18
        - os: windows-2019
          python-architecture: x64
          python-version: 2.7.18
        - os: windows-2016
          python-architecture: x64
          python-version: 2.7.18
        - os: windows-2022
          python-architecture: x86
          python-version: 2.7.18
        - os: windows-2019
          python-architecture: x86
          python-version: 2.7.18
        - os: windows-2016
          python-architecture: x86
          python-version: 2.7.18
name: Test Merseinne Twister
'on':
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
