name: Test Merseinne Twister
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  do-the-twist:
    name: "Run the Twister"
    run-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version:
          - '3.11.0-alpha1'
          - '3.10'
          - '3.9'
          - '3.8'
          - '3.7'
          - '3.6'
          - '3.5'
          - '3.4'
          - '2.7'
          - 'pypy-3.8'
          - 'pypy-3.7'
          - 'pypy-3.6'
          - 'pypy-2.7'
        python-architecture: [x86, x64]
        os:
          - "windows-2022"
          - "windows-2019"
          - "windows-2016"
          - "ubuntu-20.04"
          - "ubuntu-18.04"
          - "macos-11"
          - "macos-10.15"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.python-architecture }}

      - run: python testme.py
