name: Test Merseinne Twister
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  do-the-twist:
    name: "Run the Twister"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.9'
          - '3.8'
          - '3.7'
          - '3.6'
          - 'pypy-3.8'
          - 'pypy-3.7'
          - 'pypy-3.6'
        python-architecture: [x64]
        os:
          - "windows-2022"
          - "windows-2019"
          - "windows-2016"
          - "ubuntu-20.04"
          - "ubuntu-18.04"
          - "macos-11"
          - "macos-10.15"

        include:
          - os: windows-2022
            python-architecture: x86

          - os: windows-2019
            python-architecture: x86

          - os: windows-2016
            python-architecture: x86

        exclude:
          - os: windows-2016
            python-version: "3.10"
            python-architecture: x86

          - os: windows-2019
            python-version: "3.10"
            python-architecture: x86

          - os: windows-2022
            python-version: "3.10"
            python-architecture: x86
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.python-architecture }}

      - run: python testme.py
